# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/maxbarlow/AES67_macos_Driver

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/maxbarlow/AES67_macos_Driver

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/opt/homebrew/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/opt/homebrew/bin/cpack --config ./CPackSourceConfig.cmake /Users/maxbarlow/AES67_macos_Driver/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/maxbarlow/AES67_macos_Driver/CMakeFiles /Users/maxbarlow/AES67_macos_Driver//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/maxbarlow/AES67_macos_Driver/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named AES67Driver

# Build rule for target.
AES67Driver: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AES67Driver
.PHONY : AES67Driver

# fast build rule for target.
AES67Driver/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES67Driver.dir/build.make CMakeFiles/AES67Driver.dir/build
.PHONY : AES67Driver/fast

#=============================================================================
# Target rules for targets named TestSDPParser

# Build rule for target.
TestSDPParser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestSDPParser
.PHONY : TestSDPParser

# fast build rule for target.
TestSDPParser/fast:
	$(MAKE) $(MAKESILENT) -f Tests/CMakeFiles/TestSDPParser.dir/build.make Tests/CMakeFiles/TestSDPParser.dir/build
.PHONY : TestSDPParser/fast

#=============================================================================
# Target rules for targets named TestChannelMapper

# Build rule for target.
TestChannelMapper: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestChannelMapper
.PHONY : TestChannelMapper

# fast build rule for target.
TestChannelMapper/fast:
	$(MAKE) $(MAKESILENT) -f Tests/CMakeFiles/TestChannelMapper.dir/build.make Tests/CMakeFiles/TestChannelMapper.dir/build
.PHONY : TestChannelMapper/fast

#=============================================================================
# Target rules for targets named TestRingBuffer

# Build rule for target.
TestRingBuffer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestRingBuffer
.PHONY : TestRingBuffer

# fast build rule for target.
TestRingBuffer/fast:
	$(MAKE) $(MAKESILENT) -f Tests/CMakeFiles/TestRingBuffer.dir/build.make Tests/CMakeFiles/TestRingBuffer.dir/build
.PHONY : TestRingBuffer/fast

#=============================================================================
# Target rules for targets named TestRTPReceiver

# Build rule for target.
TestRTPReceiver: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestRTPReceiver
.PHONY : TestRTPReceiver

# fast build rule for target.
TestRTPReceiver/fast:
	$(MAKE) $(MAKESILENT) -f Tests/CMakeFiles/TestRTPReceiver.dir/build.make Tests/CMakeFiles/TestRTPReceiver.dir/build
.PHONY : TestRTPReceiver/fast

#=============================================================================
# Target rules for targets named TestRTPTransmitter

# Build rule for target.
TestRTPTransmitter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestRTPTransmitter
.PHONY : TestRTPTransmitter

# fast build rule for target.
TestRTPTransmitter/fast:
	$(MAKE) $(MAKESILENT) -f Tests/CMakeFiles/TestRTPTransmitter.dir/build.make Tests/CMakeFiles/TestRTPTransmitter.dir/build
.PHONY : TestRTPTransmitter/fast

#=============================================================================
# Target rules for targets named TestPTPClock

# Build rule for target.
TestPTPClock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestPTPClock
.PHONY : TestPTPClock

# fast build rule for target.
TestPTPClock/fast:
	$(MAKE) $(MAKESILENT) -f Tests/CMakeFiles/TestPTPClock.dir/build.make Tests/CMakeFiles/TestPTPClock.dir/build
.PHONY : TestPTPClock/fast

#=============================================================================
# Target rules for targets named TestStreamManager

# Build rule for target.
TestStreamManager: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestStreamManager
.PHONY : TestStreamManager

# fast build rule for target.
TestStreamManager/fast:
	$(MAKE) $(MAKESILENT) -f Tests/CMakeFiles/TestStreamManager.dir/build.make Tests/CMakeFiles/TestStreamManager.dir/build
.PHONY : TestStreamManager/fast

#=============================================================================
# Target rules for targets named TestMultiStream

# Build rule for target.
TestMultiStream: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestMultiStream
.PHONY : TestMultiStream

# fast build rule for target.
TestMultiStream/fast:
	$(MAKE) $(MAKESILENT) -f Tests/CMakeFiles/TestMultiStream.dir/build.make Tests/CMakeFiles/TestMultiStream.dir/build
.PHONY : TestMultiStream/fast

#=============================================================================
# Target rules for targets named BenchmarkIOHandler

# Build rule for target.
BenchmarkIOHandler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BenchmarkIOHandler
.PHONY : BenchmarkIOHandler

# fast build rule for target.
BenchmarkIOHandler/fast:
	$(MAKE) $(MAKESILENT) -f Tests/CMakeFiles/BenchmarkIOHandler.dir/build.make Tests/CMakeFiles/BenchmarkIOHandler.dir/build
.PHONY : BenchmarkIOHandler/fast

#=============================================================================
# Target rules for targets named SimpleSDPParse

# Build rule for target.
SimpleSDPParse: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SimpleSDPParse
.PHONY : SimpleSDPParse

# fast build rule for target.
SimpleSDPParse/fast:
	$(MAKE) $(MAKESILENT) -f Examples/CMakeFiles/SimpleSDPParse.dir/build.make Examples/CMakeFiles/SimpleSDPParse.dir/build
.PHONY : SimpleSDPParse/fast

#=============================================================================
# Target rules for targets named ChannelMapperDemo

# Build rule for target.
ChannelMapperDemo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ChannelMapperDemo
.PHONY : ChannelMapperDemo

# fast build rule for target.
ChannelMapperDemo/fast:
	$(MAKE) $(MAKESILENT) -f Examples/CMakeFiles/ChannelMapperDemo.dir/build.make Examples/CMakeFiles/ChannelMapperDemo.dir/build
.PHONY : ChannelMapperDemo/fast

Driver/AES67Device.o: Driver/AES67Device.cpp.o
.PHONY : Driver/AES67Device.o

# target to build an object file
Driver/AES67Device.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES67Driver.dir/build.make CMakeFiles/AES67Driver.dir/Driver/AES67Device.cpp.o
.PHONY : Driver/AES67Device.cpp.o

Driver/AES67Device.i: Driver/AES67Device.cpp.i
.PHONY : Driver/AES67Device.i

# target to preprocess a source file
Driver/AES67Device.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES67Driver.dir/build.make CMakeFiles/AES67Driver.dir/Driver/AES67Device.cpp.i
.PHONY : Driver/AES67Device.cpp.i

Driver/AES67Device.s: Driver/AES67Device.cpp.s
.PHONY : Driver/AES67Device.s

# target to generate assembly for a file
Driver/AES67Device.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES67Driver.dir/build.make CMakeFiles/AES67Driver.dir/Driver/AES67Device.cpp.s
.PHONY : Driver/AES67Device.cpp.s

Driver/AES67IOHandler.o: Driver/AES67IOHandler.cpp.o
.PHONY : Driver/AES67IOHandler.o

# target to build an object file
Driver/AES67IOHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES67Driver.dir/build.make CMakeFiles/AES67Driver.dir/Driver/AES67IOHandler.cpp.o
.PHONY : Driver/AES67IOHandler.cpp.o

Driver/AES67IOHandler.i: Driver/AES67IOHandler.cpp.i
.PHONY : Driver/AES67IOHandler.i

# target to preprocess a source file
Driver/AES67IOHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES67Driver.dir/build.make CMakeFiles/AES67Driver.dir/Driver/AES67IOHandler.cpp.i
.PHONY : Driver/AES67IOHandler.cpp.i

Driver/AES67IOHandler.s: Driver/AES67IOHandler.cpp.s
.PHONY : Driver/AES67IOHandler.s

# target to generate assembly for a file
Driver/AES67IOHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES67Driver.dir/build.make CMakeFiles/AES67Driver.dir/Driver/AES67IOHandler.cpp.s
.PHONY : Driver/AES67IOHandler.cpp.s

Driver/PlugInMain.o: Driver/PlugInMain.cpp.o
.PHONY : Driver/PlugInMain.o

# target to build an object file
Driver/PlugInMain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES67Driver.dir/build.make CMakeFiles/AES67Driver.dir/Driver/PlugInMain.cpp.o
.PHONY : Driver/PlugInMain.cpp.o

Driver/PlugInMain.i: Driver/PlugInMain.cpp.i
.PHONY : Driver/PlugInMain.i

# target to preprocess a source file
Driver/PlugInMain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES67Driver.dir/build.make CMakeFiles/AES67Driver.dir/Driver/PlugInMain.cpp.i
.PHONY : Driver/PlugInMain.cpp.i

Driver/PlugInMain.s: Driver/PlugInMain.cpp.s
.PHONY : Driver/PlugInMain.s

# target to generate assembly for a file
Driver/PlugInMain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES67Driver.dir/build.make CMakeFiles/AES67Driver.dir/Driver/PlugInMain.cpp.s
.PHONY : Driver/PlugInMain.cpp.s

Driver/SDPParser.o: Driver/SDPParser.cpp.o
.PHONY : Driver/SDPParser.o

# target to build an object file
Driver/SDPParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES67Driver.dir/build.make CMakeFiles/AES67Driver.dir/Driver/SDPParser.cpp.o
.PHONY : Driver/SDPParser.cpp.o

Driver/SDPParser.i: Driver/SDPParser.cpp.i
.PHONY : Driver/SDPParser.i

# target to preprocess a source file
Driver/SDPParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES67Driver.dir/build.make CMakeFiles/AES67Driver.dir/Driver/SDPParser.cpp.i
.PHONY : Driver/SDPParser.cpp.i

Driver/SDPParser.s: Driver/SDPParser.cpp.s
.PHONY : Driver/SDPParser.s

# target to generate assembly for a file
Driver/SDPParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES67Driver.dir/build.make CMakeFiles/AES67Driver.dir/Driver/SDPParser.cpp.s
.PHONY : Driver/SDPParser.cpp.s

NetworkEngine/Discovery/RTSPClient.o: NetworkEngine/Discovery/RTSPClient.cpp.o
.PHONY : NetworkEngine/Discovery/RTSPClient.o

# target to build an object file
NetworkEngine/Discovery/RTSPClient.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES67Driver.dir/build.make CMakeFiles/AES67Driver.dir/NetworkEngine/Discovery/RTSPClient.cpp.o
.PHONY : NetworkEngine/Discovery/RTSPClient.cpp.o

NetworkEngine/Discovery/RTSPClient.i: NetworkEngine/Discovery/RTSPClient.cpp.i
.PHONY : NetworkEngine/Discovery/RTSPClient.i

# target to preprocess a source file
NetworkEngine/Discovery/RTSPClient.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES67Driver.dir/build.make CMakeFiles/AES67Driver.dir/NetworkEngine/Discovery/RTSPClient.cpp.i
.PHONY : NetworkEngine/Discovery/RTSPClient.cpp.i

NetworkEngine/Discovery/RTSPClient.s: NetworkEngine/Discovery/RTSPClient.cpp.s
.PHONY : NetworkEngine/Discovery/RTSPClient.s

# target to generate assembly for a file
NetworkEngine/Discovery/RTSPClient.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES67Driver.dir/build.make CMakeFiles/AES67Driver.dir/NetworkEngine/Discovery/RTSPClient.cpp.s
.PHONY : NetworkEngine/Discovery/RTSPClient.cpp.s

NetworkEngine/Discovery/SAPListener.o: NetworkEngine/Discovery/SAPListener.cpp.o
.PHONY : NetworkEngine/Discovery/SAPListener.o

# target to build an object file
NetworkEngine/Discovery/SAPListener.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES67Driver.dir/build.make CMakeFiles/AES67Driver.dir/NetworkEngine/Discovery/SAPListener.cpp.o
.PHONY : NetworkEngine/Discovery/SAPListener.cpp.o

NetworkEngine/Discovery/SAPListener.i: NetworkEngine/Discovery/SAPListener.cpp.i
.PHONY : NetworkEngine/Discovery/SAPListener.i

# target to preprocess a source file
NetworkEngine/Discovery/SAPListener.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES67Driver.dir/build.make CMakeFiles/AES67Driver.dir/NetworkEngine/Discovery/SAPListener.cpp.i
.PHONY : NetworkEngine/Discovery/SAPListener.cpp.i

NetworkEngine/Discovery/SAPListener.s: NetworkEngine/Discovery/SAPListener.cpp.s
.PHONY : NetworkEngine/Discovery/SAPListener.s

# target to generate assembly for a file
NetworkEngine/Discovery/SAPListener.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES67Driver.dir/build.make CMakeFiles/AES67Driver.dir/NetworkEngine/Discovery/SAPListener.cpp.s
.PHONY : NetworkEngine/Discovery/SAPListener.cpp.s

NetworkEngine/DoPDecoder.o: NetworkEngine/DoPDecoder.cpp.o
.PHONY : NetworkEngine/DoPDecoder.o

# target to build an object file
NetworkEngine/DoPDecoder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES67Driver.dir/build.make CMakeFiles/AES67Driver.dir/NetworkEngine/DoPDecoder.cpp.o
.PHONY : NetworkEngine/DoPDecoder.cpp.o

NetworkEngine/DoPDecoder.i: NetworkEngine/DoPDecoder.cpp.i
.PHONY : NetworkEngine/DoPDecoder.i

# target to preprocess a source file
NetworkEngine/DoPDecoder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES67Driver.dir/build.make CMakeFiles/AES67Driver.dir/NetworkEngine/DoPDecoder.cpp.i
.PHONY : NetworkEngine/DoPDecoder.cpp.i

NetworkEngine/DoPDecoder.s: NetworkEngine/DoPDecoder.cpp.s
.PHONY : NetworkEngine/DoPDecoder.s

# target to generate assembly for a file
NetworkEngine/DoPDecoder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES67Driver.dir/build.make CMakeFiles/AES67Driver.dir/NetworkEngine/DoPDecoder.cpp.s
.PHONY : NetworkEngine/DoPDecoder.cpp.s

NetworkEngine/PTP/PTPClock.o: NetworkEngine/PTP/PTPClock.cpp.o
.PHONY : NetworkEngine/PTP/PTPClock.o

# target to build an object file
NetworkEngine/PTP/PTPClock.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES67Driver.dir/build.make CMakeFiles/AES67Driver.dir/NetworkEngine/PTP/PTPClock.cpp.o
.PHONY : NetworkEngine/PTP/PTPClock.cpp.o

NetworkEngine/PTP/PTPClock.i: NetworkEngine/PTP/PTPClock.cpp.i
.PHONY : NetworkEngine/PTP/PTPClock.i

# target to preprocess a source file
NetworkEngine/PTP/PTPClock.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES67Driver.dir/build.make CMakeFiles/AES67Driver.dir/NetworkEngine/PTP/PTPClock.cpp.i
.PHONY : NetworkEngine/PTP/PTPClock.cpp.i

NetworkEngine/PTP/PTPClock.s: NetworkEngine/PTP/PTPClock.cpp.s
.PHONY : NetworkEngine/PTP/PTPClock.s

# target to generate assembly for a file
NetworkEngine/PTP/PTPClock.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES67Driver.dir/build.make CMakeFiles/AES67Driver.dir/NetworkEngine/PTP/PTPClock.cpp.s
.PHONY : NetworkEngine/PTP/PTPClock.cpp.s

NetworkEngine/RTP/RTPReceiver.o: NetworkEngine/RTP/RTPReceiver.cpp.o
.PHONY : NetworkEngine/RTP/RTPReceiver.o

# target to build an object file
NetworkEngine/RTP/RTPReceiver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES67Driver.dir/build.make CMakeFiles/AES67Driver.dir/NetworkEngine/RTP/RTPReceiver.cpp.o
.PHONY : NetworkEngine/RTP/RTPReceiver.cpp.o

NetworkEngine/RTP/RTPReceiver.i: NetworkEngine/RTP/RTPReceiver.cpp.i
.PHONY : NetworkEngine/RTP/RTPReceiver.i

# target to preprocess a source file
NetworkEngine/RTP/RTPReceiver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES67Driver.dir/build.make CMakeFiles/AES67Driver.dir/NetworkEngine/RTP/RTPReceiver.cpp.i
.PHONY : NetworkEngine/RTP/RTPReceiver.cpp.i

NetworkEngine/RTP/RTPReceiver.s: NetworkEngine/RTP/RTPReceiver.cpp.s
.PHONY : NetworkEngine/RTP/RTPReceiver.s

# target to generate assembly for a file
NetworkEngine/RTP/RTPReceiver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES67Driver.dir/build.make CMakeFiles/AES67Driver.dir/NetworkEngine/RTP/RTPReceiver.cpp.s
.PHONY : NetworkEngine/RTP/RTPReceiver.cpp.s

NetworkEngine/RTP/RTPTransmitter.o: NetworkEngine/RTP/RTPTransmitter.cpp.o
.PHONY : NetworkEngine/RTP/RTPTransmitter.o

# target to build an object file
NetworkEngine/RTP/RTPTransmitter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES67Driver.dir/build.make CMakeFiles/AES67Driver.dir/NetworkEngine/RTP/RTPTransmitter.cpp.o
.PHONY : NetworkEngine/RTP/RTPTransmitter.cpp.o

NetworkEngine/RTP/RTPTransmitter.i: NetworkEngine/RTP/RTPTransmitter.cpp.i
.PHONY : NetworkEngine/RTP/RTPTransmitter.i

# target to preprocess a source file
NetworkEngine/RTP/RTPTransmitter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES67Driver.dir/build.make CMakeFiles/AES67Driver.dir/NetworkEngine/RTP/RTPTransmitter.cpp.i
.PHONY : NetworkEngine/RTP/RTPTransmitter.cpp.i

NetworkEngine/RTP/RTPTransmitter.s: NetworkEngine/RTP/RTPTransmitter.cpp.s
.PHONY : NetworkEngine/RTP/RTPTransmitter.s

# target to generate assembly for a file
NetworkEngine/RTP/RTPTransmitter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES67Driver.dir/build.make CMakeFiles/AES67Driver.dir/NetworkEngine/RTP/RTPTransmitter.cpp.s
.PHONY : NetworkEngine/RTP/RTPTransmitter.cpp.s

NetworkEngine/RTP/SimpleRTP.o: NetworkEngine/RTP/SimpleRTP.cpp.o
.PHONY : NetworkEngine/RTP/SimpleRTP.o

# target to build an object file
NetworkEngine/RTP/SimpleRTP.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES67Driver.dir/build.make CMakeFiles/AES67Driver.dir/NetworkEngine/RTP/SimpleRTP.cpp.o
.PHONY : NetworkEngine/RTP/SimpleRTP.cpp.o

NetworkEngine/RTP/SimpleRTP.i: NetworkEngine/RTP/SimpleRTP.cpp.i
.PHONY : NetworkEngine/RTP/SimpleRTP.i

# target to preprocess a source file
NetworkEngine/RTP/SimpleRTP.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES67Driver.dir/build.make CMakeFiles/AES67Driver.dir/NetworkEngine/RTP/SimpleRTP.cpp.i
.PHONY : NetworkEngine/RTP/SimpleRTP.cpp.i

NetworkEngine/RTP/SimpleRTP.s: NetworkEngine/RTP/SimpleRTP.cpp.s
.PHONY : NetworkEngine/RTP/SimpleRTP.s

# target to generate assembly for a file
NetworkEngine/RTP/SimpleRTP.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES67Driver.dir/build.make CMakeFiles/AES67Driver.dir/NetworkEngine/RTP/SimpleRTP.cpp.s
.PHONY : NetworkEngine/RTP/SimpleRTP.cpp.s

NetworkEngine/StreamChannelMapper.o: NetworkEngine/StreamChannelMapper.cpp.o
.PHONY : NetworkEngine/StreamChannelMapper.o

# target to build an object file
NetworkEngine/StreamChannelMapper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES67Driver.dir/build.make CMakeFiles/AES67Driver.dir/NetworkEngine/StreamChannelMapper.cpp.o
.PHONY : NetworkEngine/StreamChannelMapper.cpp.o

NetworkEngine/StreamChannelMapper.i: NetworkEngine/StreamChannelMapper.cpp.i
.PHONY : NetworkEngine/StreamChannelMapper.i

# target to preprocess a source file
NetworkEngine/StreamChannelMapper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES67Driver.dir/build.make CMakeFiles/AES67Driver.dir/NetworkEngine/StreamChannelMapper.cpp.i
.PHONY : NetworkEngine/StreamChannelMapper.cpp.i

NetworkEngine/StreamChannelMapper.s: NetworkEngine/StreamChannelMapper.cpp.s
.PHONY : NetworkEngine/StreamChannelMapper.s

# target to generate assembly for a file
NetworkEngine/StreamChannelMapper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES67Driver.dir/build.make CMakeFiles/AES67Driver.dir/NetworkEngine/StreamChannelMapper.cpp.s
.PHONY : NetworkEngine/StreamChannelMapper.cpp.s

NetworkEngine/StreamConfig.o: NetworkEngine/StreamConfig.cpp.o
.PHONY : NetworkEngine/StreamConfig.o

# target to build an object file
NetworkEngine/StreamConfig.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES67Driver.dir/build.make CMakeFiles/AES67Driver.dir/NetworkEngine/StreamConfig.cpp.o
.PHONY : NetworkEngine/StreamConfig.cpp.o

NetworkEngine/StreamConfig.i: NetworkEngine/StreamConfig.cpp.i
.PHONY : NetworkEngine/StreamConfig.i

# target to preprocess a source file
NetworkEngine/StreamConfig.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES67Driver.dir/build.make CMakeFiles/AES67Driver.dir/NetworkEngine/StreamConfig.cpp.i
.PHONY : NetworkEngine/StreamConfig.cpp.i

NetworkEngine/StreamConfig.s: NetworkEngine/StreamConfig.cpp.s
.PHONY : NetworkEngine/StreamConfig.s

# target to generate assembly for a file
NetworkEngine/StreamConfig.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES67Driver.dir/build.make CMakeFiles/AES67Driver.dir/NetworkEngine/StreamConfig.cpp.s
.PHONY : NetworkEngine/StreamConfig.cpp.s

NetworkEngine/StreamManager.o: NetworkEngine/StreamManager.cpp.o
.PHONY : NetworkEngine/StreamManager.o

# target to build an object file
NetworkEngine/StreamManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES67Driver.dir/build.make CMakeFiles/AES67Driver.dir/NetworkEngine/StreamManager.cpp.o
.PHONY : NetworkEngine/StreamManager.cpp.o

NetworkEngine/StreamManager.i: NetworkEngine/StreamManager.cpp.i
.PHONY : NetworkEngine/StreamManager.i

# target to preprocess a source file
NetworkEngine/StreamManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES67Driver.dir/build.make CMakeFiles/AES67Driver.dir/NetworkEngine/StreamManager.cpp.i
.PHONY : NetworkEngine/StreamManager.cpp.i

NetworkEngine/StreamManager.s: NetworkEngine/StreamManager.cpp.s
.PHONY : NetworkEngine/StreamManager.s

# target to generate assembly for a file
NetworkEngine/StreamManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES67Driver.dir/build.make CMakeFiles/AES67Driver.dir/NetworkEngine/StreamManager.cpp.s
.PHONY : NetworkEngine/StreamManager.cpp.s

Shared/Config.o: Shared/Config.cpp.o
.PHONY : Shared/Config.o

# target to build an object file
Shared/Config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES67Driver.dir/build.make CMakeFiles/AES67Driver.dir/Shared/Config.cpp.o
.PHONY : Shared/Config.cpp.o

Shared/Config.i: Shared/Config.cpp.i
.PHONY : Shared/Config.i

# target to preprocess a source file
Shared/Config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES67Driver.dir/build.make CMakeFiles/AES67Driver.dir/Shared/Config.cpp.i
.PHONY : Shared/Config.cpp.i

Shared/Config.s: Shared/Config.cpp.s
.PHONY : Shared/Config.s

# target to generate assembly for a file
Shared/Config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES67Driver.dir/build.make CMakeFiles/AES67Driver.dir/Shared/Config.cpp.s
.PHONY : Shared/Config.cpp.s

Shared/Types.o: Shared/Types.cpp.o
.PHONY : Shared/Types.o

# target to build an object file
Shared/Types.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES67Driver.dir/build.make CMakeFiles/AES67Driver.dir/Shared/Types.cpp.o
.PHONY : Shared/Types.cpp.o

Shared/Types.i: Shared/Types.cpp.i
.PHONY : Shared/Types.i

# target to preprocess a source file
Shared/Types.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES67Driver.dir/build.make CMakeFiles/AES67Driver.dir/Shared/Types.cpp.i
.PHONY : Shared/Types.cpp.i

Shared/Types.s: Shared/Types.cpp.s
.PHONY : Shared/Types.s

# target to generate assembly for a file
Shared/Types.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES67Driver.dir/build.make CMakeFiles/AES67Driver.dir/Shared/Types.cpp.s
.PHONY : Shared/Types.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... AES67Driver"
	@echo "... BenchmarkIOHandler"
	@echo "... ChannelMapperDemo"
	@echo "... SimpleSDPParse"
	@echo "... TestChannelMapper"
	@echo "... TestMultiStream"
	@echo "... TestPTPClock"
	@echo "... TestRTPReceiver"
	@echo "... TestRTPTransmitter"
	@echo "... TestRingBuffer"
	@echo "... TestSDPParser"
	@echo "... TestStreamManager"
	@echo "... Driver/AES67Device.o"
	@echo "... Driver/AES67Device.i"
	@echo "... Driver/AES67Device.s"
	@echo "... Driver/AES67IOHandler.o"
	@echo "... Driver/AES67IOHandler.i"
	@echo "... Driver/AES67IOHandler.s"
	@echo "... Driver/PlugInMain.o"
	@echo "... Driver/PlugInMain.i"
	@echo "... Driver/PlugInMain.s"
	@echo "... Driver/SDPParser.o"
	@echo "... Driver/SDPParser.i"
	@echo "... Driver/SDPParser.s"
	@echo "... NetworkEngine/Discovery/RTSPClient.o"
	@echo "... NetworkEngine/Discovery/RTSPClient.i"
	@echo "... NetworkEngine/Discovery/RTSPClient.s"
	@echo "... NetworkEngine/Discovery/SAPListener.o"
	@echo "... NetworkEngine/Discovery/SAPListener.i"
	@echo "... NetworkEngine/Discovery/SAPListener.s"
	@echo "... NetworkEngine/DoPDecoder.o"
	@echo "... NetworkEngine/DoPDecoder.i"
	@echo "... NetworkEngine/DoPDecoder.s"
	@echo "... NetworkEngine/PTP/PTPClock.o"
	@echo "... NetworkEngine/PTP/PTPClock.i"
	@echo "... NetworkEngine/PTP/PTPClock.s"
	@echo "... NetworkEngine/RTP/RTPReceiver.o"
	@echo "... NetworkEngine/RTP/RTPReceiver.i"
	@echo "... NetworkEngine/RTP/RTPReceiver.s"
	@echo "... NetworkEngine/RTP/RTPTransmitter.o"
	@echo "... NetworkEngine/RTP/RTPTransmitter.i"
	@echo "... NetworkEngine/RTP/RTPTransmitter.s"
	@echo "... NetworkEngine/RTP/SimpleRTP.o"
	@echo "... NetworkEngine/RTP/SimpleRTP.i"
	@echo "... NetworkEngine/RTP/SimpleRTP.s"
	@echo "... NetworkEngine/StreamChannelMapper.o"
	@echo "... NetworkEngine/StreamChannelMapper.i"
	@echo "... NetworkEngine/StreamChannelMapper.s"
	@echo "... NetworkEngine/StreamConfig.o"
	@echo "... NetworkEngine/StreamConfig.i"
	@echo "... NetworkEngine/StreamConfig.s"
	@echo "... NetworkEngine/StreamManager.o"
	@echo "... NetworkEngine/StreamManager.i"
	@echo "... NetworkEngine/StreamManager.s"
	@echo "... Shared/Config.o"
	@echo "... Shared/Config.i"
	@echo "... Shared/Config.s"
	@echo "... Shared/Types.o"
	@echo "... Shared/Types.i"
	@echo "... Shared/Types.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

